### ISSUE TITLE
v8.0.0 stabilization work

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#495]
This is a placeholder issue for all work that remains to be done towards a v8 release of `tss-esapi`.

- [ ] TpmsContext will be moved into structures and have it's name changed to SavedTpmContext.

**Comment by Superhepper** [comment]
Increase minimum supported Rust version
Increase minimum supported tpm2-tss version (To at least 3.0 but ideally I would like to see something greater).

**Comment by Superhepper** [comment]
Make serde an optional dependency.

**Comment by wiktor-k** [comment]
I'm not sure if it's tracked somewhere else independently but I had to use `generate bindings` feature to get the first alpha to compile in my crate: https://github.com/wiktor-k/tpm-box/blob/main/Cargo.toml#L18

It'd be nice to fix that before releasing 8.0.

**Comment by Superhepper** [comment]
> I'm not sure if it's tracked somewhere else independently but I had to use `generate bindings` feature to get the first alpha to compile in my crate: https://github.com/wiktor-k/tpm-box/blob/main/Cargo.toml#L18
> 
> It'd be nice to fix that before releasing 8.0.

That will probably be fixed when  #505 is merged.

**Comment by wiktor-k** [comment]
> That will probably be fixed when #505 is merged.

Hm... it doesn't seem so from my tests:

1. clone [tpm-box](https://github.com/wiktor-k/tpm-box)
2. change the dep line to: `tss-esapi={ version = "8.0.0-alpha", git ="https://github.com/parallaxsecond/rust-tss-esapi", rev = "refs/pull/505/head" }`
3. `cargo check`

It gives me:

```
    Checking tss-esapi v8.0.0-alpha (https://github.com/parallaxsecond/rust-tss-esapi?rev=refs/pull/505/head#1451c519)
error[E0432]: unresolved import `crate::tss2_esys::TPMU_SENSITIVE_CREATE`
   --> /home/wiktor/.cargo/git/checkouts/rust-tss-esapi-acac77377da9bd28/1451c51/tss-esapi/src/structures/buffers.rs:364:17
    |
364 |             use crate::tss2_esys::TPMU_SENSITIVE_CREATE;
    |                 ^^^^^^^^^^^^^^^^^^---------------------
    |                 |                 |
    |                 |                 help: a similar name exists in the module: `TPMS_SENSITIVE_CREATE`
    |                 no `TPMU_SENSITIVE_CREATE` in the root
```

The commit referenced in the output is the same as in your PR... or maybe I'm holding it wrong somehow? :thinking:

**Comment by Superhepper** [comment]
Hrmm that is not what I expected. Well we can rather easily determine where the problem lies by looking at the generated code and see if the type exists.

**Comment by wiktor-k** [comment]
It's interesting that the build works on the PR-level but fails here... totally not something I expected :/

**Comment by Superhepper** [comment]
It can be that I made a mistake so it always generates the bindings even when it should not. I will have to look into this.

**Comment by wiktor-k** [comment]
Thank you :pray:

**Comment by Superhepper** [comment]
Yup it is my mistake. Because I forgot to change a parameter in the test script that determines what flags to enable. So it will always generate bindings and never use the ones commited.

**Comment by wiktor-k** [comment]
> Yup it is my mistake. Because I forgot to change a parameter in the test script that determines what flags to enable. So it will always generate bindings and never use the ones commited.

Well... then it's quite funny because appending `features = ["generate-bindings"],` in my Cargo.toml makes it work on my end :sweat_smile:

**Comment by Superhepper** [comment]
> Yup it is my mistake. Because I forgot to change a parameter in the test script that determines what flags to enable. So it will always generate bindings and never use the ones commited.\n\nWell... then it's quite funny because appending features = [\"generate-bindings\"], in my Cargo.toml makes it work on my end 😅

No, that is expected. Because in that PR all that is tested is that "generate-bindings" works. The code is never tested using the committed bindings due to my mistake.

**Comment by Superhepper** [comment]
> > Yup it is my mistake. Because I forgot to change a parameter in the test script that determines what flags to enable. So it will always generate bindings and never use the ones commited.\n\nWell... then it's quite funny because appending features = ["generate-bindings"], in my Cargo.toml makes it work on my end 😅
> 
> No, that is expected. Because in that PR all that is tested is that "generate-bindings" works. The code is never tested using the committed bindings due to my mistake.

This should be fixed now. Please try again @wiktor-k

**Comment by wiktor-k** [comment]
I've updated via `cargo update`:

```
Updating tss-esapi v8.0.0-alpha (https://github.com/parallaxsecond/rust-tss-esapi?rev=refs/pull/505/head#1451c519) -> #8ab0de2f
    Updating tss-esapi-sys v0.5.0 (https://github.com/parallaxsecond/rust-tss-esapi?rev=refs/pull/505/head#1451c519) -> #8ab0de2f
```

And it still fails:

```
error[E0432]: unresolved import `crate::tss2_esys::TPMU_SENSITIVE_CREATE`
   --> /home/wiktor/.cargo/git/checkouts/rust-tss-esapi-acac77377da9bd28/8ab0de2/tss-esapi/src/structures/buffers.rs:364:17
    |
364 |             use crate::tss2_esys::TPMU_SENSITIVE_CREATE;
    |                 ^^^^^^^^^^^^^^^^^^---------------------
    |                 |                 |
    |                 |                 help: a similar name exists in the module: `TPMS_SENSITIVE_CREATE`
    |                 no `TPMU_SENSITIVE_CREATE` in the root
```

Interesting that it's just a one letter "typo" (S <-> U). :/

**Comment by wiktor-k** [comment]
```
$ pkg-config --modversion tss2-esys
4.0.1
```

Are you able to reproduce building `tpm-box` locally using [these instructions](https://github.com/parallaxsecond/rust-tss-esapi/issues/495#issuecomment-1963563114)? Maybe it's something on my end but previous versions worked fine :thinking:

**Comment by Superhepper** [comment]
I am not sure when I will have time to look at it. But I will investigate.

**Comment by wiktor-k** [comment]
> I am not sure when I will have time to look at it. But I will investigate.

Wait a minute let me ask some people that for sure have plenty of time :smirk: : @ionut-arm, @tgonzalezorlandoarm could you help check if you also get the same error as I do? Just follow this simple 3 step instruction: https://github.com/parallaxsecond/rust-tss-esapi/issues/495#issuecomment-1963563114

**Comment by tgonzalezorlandoarm** [comment]
@wiktor-k I'll take a look today :)

**Comment by tgonzalezorlandoarm** [comment]
@wiktor-k @Superhepper 

So, I took a look:

1. I think "version" was missing for "package" on the Cargo.toml of tpm-box. I put a dummy version.
2. I got your error.
3. I then realized that the `TPMU_SENSITIVE_CREATE` failure was being triggered when `TSS_VERSION > 4.0.0` as indicated in [here](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/src/structures/buffers.rs#L363) and [here](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/build.rs#L41).
4. And the bindings were generated `TSS_VERSION = 3.2.2` as indicated [here](https://github.com/parallaxsecond/rust-tss-esapi/pull/505/files#diff-02108cee9d93170e6bba00f4cd8350bd4ba86b53975e42c09747964750a20d98R2).
5. So basically it was a matter of the `TSS_VERSION` on the docker image I was using.
6. I was building the docker image as imposed by the ci.yml [here](https://github.com/parallaxsecond/rust-tss-esapi/pull/505/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR53), which uses `TSS_VERSION > 4.0.0`.

I was able to have a successful build with:

1. `rust-tss-esapi$ docker build -t ubuntucontainer tss-esapi/tests/ --build-arg TPM2_TSS_VERSION=3.2.2 --file tss-esapi/tests/Dockerfile-ubuntu`
2. `tpm-box$ docker run -v $(pwd):/tmp/tpm-box -w /tmp/tpm-box -it ubuntucontainer`
3. `cargo clean` (This is just in case you have abn old build there that would cause issues).
4. `cargo check`

Hope this helps?

**Comment by ionut-arm** [comment]
I'm adding a new task for the stabilization work: fixing [the failing doc build](https://docs.rs/crate/tss-esapi/8.0.0-alpha/builds/1118628).

**Comment by Superhepper** [comment]
> I'm adding a new task for the stabilization work: fixing [the failing doc build](https://docs.rs/crate/tss-esapi/8.0.0-alpha/builds/1118628).

That thing is really strange. If I have understood things correctly then the ```DEP_``` environment variables are produced by cargo when the sys crate prints out link-information (e.g. ```println!("cargo:rustc-link-lib={}", lib_name);```). So it seems as the build script in the sys crate have not been run at all.

**Comment by rucoder** [comment]
@ionut-arm it would be great to finish and merge work started in https://github.com/parallaxsecond/rust-tss-esapi/pull/537
I will allow easier integration of tss-esapi with rustls to use TPM in TLS handshake. It is required for example for https://github.com/lf-edge/eve which uses TPM to generate device keys/certificates which are used for client authentication during TLS handshake.  It is currently written in go but  I'm porting base EVE lient into rust. I have to manually implement corresponding rustls trait now using low level api of rust-tss-esapi

**Comment by wiktor-k** [comment]
> it would be great to finish and merge work started in https://github.com/parallaxsecond/rust-tss-esapi/pull/537

I think that PR is a good idea and I'm looking forward to seeing it merged too but I think we'd need to ask @baloo about it.

**Comment by baloo** [comment]
> I think that PR is a good idea and I'm looking forward to seeing it merged too but I think we'd need to ask [@baloo](https://github.com/baloo) about it.

Rebased and cleaned up the best I could, would love another round of review on it.

**Comment by G1gg1L3s** [comment]
Hi! Is there anything I can do to help move the 8.0.0 release forward?

**Comment by Superhepper** [comment]
> Hi! Is there anything I can do to help move the 8.0.0 release forward?

If you happen to have any experience with setting up Github actions CI jobs for for windows environment, it would be awesome if you could try to get the bundled feature tested under windows. As first step it would fantastic if the CI could at least build the crate on windows using the `bundled` feature. And maybe in the future get it to to run the tests using the TBS tcti.

**Comment by ionut-arm** [comment]
Any appetite to revive this and push through to get to a stable v8?

From the list above, I think the MSRV has been addressed. We'd probably find out whether the doc issue is still a thing from another alpha release.

There are quite a few PRs open, I'll need to check whether any of them breaks the API.

**Comment by Superhepper** [comment]
I think the doc is not an issue any more. I did some work on it and added a CI test for it. So https://docs.rs/crate/tss-esapi/8.0.0-alpha.2 builds fine.

And we have updated MSRV to something reasonable.

So I think we are actually in a pretty good shape to release. I am not sure how many people that have tested alpha2 release. But we have not received any Issues related to it so I assume that either no one has tested it or it works perfectly.

**Comment by ionut-arm** [comment]
> I am not sure how many people that have tested alpha2 release. 

Indeed, that's the problem with these alpha releases. You need to make sure they work for everyone, but people don't generally see / notice them.

**Comment by ionut-arm** [comment]
NOTICE: I'm hoping to release new alphas for both `tss-esapi` and `tss-esapi-sys` per the Slack channel request. This shouldn't really be a big issue or require any special preparation. But hopefully with the next alpha we can try to move towards stability, and follow that with a beta.
